// Node 22; starts a local dev server and stops it on completion. No production build.
const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const output=process.cwd()+'/.cache/ai-visual-inspection/browser';fs.mkdirSync(output,{recursive:true});
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--webpack','--hostname','127.0.0.1','--port','3100'],{stdio:['ignore','pipe','pipe'],detached:true});
let log='';server.stdout.on('data',x=>log+=x);server.stderr.on('data',x=>log+=x);
let browser, page; const verified=[], measurements={}; let failure=null;const stop=()=>{try{process.kill(-server.pid,'SIGTERM');}catch{}};
const deadline=setTimeout(()=>{stop();process.exit(124)},175000);
(async()=>{
 for(let i=0;i<60;i++){try{const r=await fetch('http://127.0.0.1:3100/tools/ai-visual-inspection');if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,500));}
 browser=await chromium.launch({headless:true});
 page=await browser.newPage({viewport:{width:1280,height:950}});
 const errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
 page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
 await page.goto('http://127.0.0.1:3100/tools/ai-visual-inspection');
 await page.getByRole('button',{name:'約5分の体験を始める'}).click();
 await page.getByRole('status').filter({hasText:'全6枚の評価完了'}).waitFor({timeout:60000});
 verified.push('initial-worker-wasm');console.log('Initial actual Worker/WASM inference passed');
 await page.getByRole('button',{name:'2. 模様と傷を比べる',exact:true}).click();
 await page.getByRole('status').filter({hasText:'全24枚の評価完了'}).waitFor({timeout:30000});
 verified.push('practice-24');
 await page.getByRole('button',{name:'次の画像',exact:true}).click();
 await page.getByRole('button',{name:'次の画像',exact:true}).click();
 await page.getByRole('checkbox').nth(1).check();
 await page.screenshot({path:output+'/desktop.png',fullPage:true});
 const initialMetrics=await page.locator('section').filter({has:page.locator('h3')}).allTextContents();
 await page.getByRole('button',{name:'同じ画像を拡大',exact:true}).click();
 await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');
 assert.equal(await page.getByRole('button',{name:'同じ画像を拡大',exact:true}).evaluate(el=>el===document.activeElement),true);
 verified.push('dialog-escape-focus');
 await page.getByRole('button',{name:'3. 教えた例を変える',exact:true}).click();
 await page.getByLabel('この例で事前学習したモデルに切り替える').selectOption('dirt-biased');
 await page.getByRole('status').filter({hasText:'全24枚の評価完了'}).waitFor({timeout:30000});
 verified.push('model-switch-dirt-biased');
 await page.getByRole('button',{name:'4. 撮影条件を変える',exact:true}).click();
 const start=Date.now();await page.getByRole('spinbutton',{name:'撮影の明るさ（倍率） 数値入力'}).fill('0.7');
 await page.getByRole('status').filter({hasText:'全24枚の評価完了'}).waitFor({timeout:30000});
 const batchMs=Date.now()-start;measurements.batchMs=batchMs;verified.push('lighting-0.7');
 await page.getByRole('button',{name:'5. 採用方法を考える',exact:true}).click();
 await page.getByRole('button',{name:'設定を固定して、別の24枚を開く',exact:true}).click();
 await page.getByRole('status').filter({hasText:'全24枚の評価完了'}).waitFor({timeout:30000});
 verified.push('confirmation-24');
 await page.getByLabel('採用候補',{exact:true}).selectOption('追加検証');await page.getByLabel('重視したこと',{exact:true}).selectOption('撮影条件への対応');
 await page.getByRole('button',{name:'この理由で振り返りを終える'}).click();
 await page.getByRole('status').filter({hasText:'一律の正解はありません'}).waitFor();
 verified.push('reflection');
 measurements.workerResources=await Promise.all(page.workers().map(worker=>worker.evaluate(()=>performance.getEntriesByType('resource').map(e=>({name:e.name,encodedBodySize:e.encodedBodySize,decodedBodySize:e.decodedBodySize,transferSize:e.transferSize,duration:e.duration})))));
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:output+'/mobile.png',fullPage:true});
 const layout=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,figures:[...document.querySelectorAll('figure')].slice(0,2).map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}})}));
 assert.ok(layout.scrollWidth<=layout.width);assert.ok(layout.figures[1].y>layout.figures[0].y);
 verified.push('mobile-viewport');measurements.layout=layout;
 // Fresh context: a real network failure must never become a good AI decision.
 const failed=await browser.newPage();await failed.route('**/models/*.onnx',r=>r.abort());
 await failed.goto('http://127.0.0.1:3100/tools/ai-visual-inspection');await failed.getByRole('button',{name:'約5分の体験を始める'}).click();
 await failed.getByRole('status').filter({hasText:'AIは未評価'}).waitFor({timeout:30000});
 verified.push('model-network-failure');await failed.close();
 assert.deepEqual(errors, [], "Unexpected browser/network errors");
 const result={errors,batchMs,layout,requests,initialMetrics:initialMetrics.slice(-3),environment:'Desktop Chromium, Next dev webpack; mobile viewport only',passed:true};
 fs.writeFileSync(output+'/report.json',JSON.stringify(result,null,2));console.log(JSON.stringify({errors,batchMs,layout,requests:requests.length}));
})().catch(async e=>{failure=String(e);console.error(e);if(page)await page.screenshot({path:output+'/failure.png',fullPage:true}).catch(()=>{});process.exitCode=1}).finally(async()=>{fs.writeFileSync(output+'/progress.json',JSON.stringify({verified,measurements,failure,environment:'Desktop Chromium / Next dev webpack; not a physical smartphone'},null,2));await browser?.close();stop();clearTimeout(deadline);fs.writeFileSync(output+'/server.log',log);});
