// Reproducible static Worker modules; no Next build or temporary tsconfig required.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const zlib = require('node:zlib');
const ts = require('typescript');
const root = 'public/ai-visual-inspection/v2';
const version = JSON.parse(fs.readFileSync('node_modules/onnxruntime-web/package.json', 'utf8')).version;
if (version !== '1.22.0') throw Error('Runtime version must be reviewed before changing');
fs.mkdirSync(`${root}/ort`, { recursive: true });
for (const name of ['ort.wasm.min.mjs', 'ort-wasm-simd-threaded.mjs', 'ort-wasm-simd-threaded.wasm']) {
  fs.copyFileSync(`node_modules/onnxruntime-web/dist/${name}`, `${root}/ort/${name}`);
}
for (const name of ['processing', 'protocol', 'runtime', 'inference.worker']) {
  const source = fs.readFileSync(`src/lib/ai-visual-inspection/${name}.ts`, 'utf8');
  const output = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ES2022, target: ts.ScriptTarget.ES2020, removeComments: false } }).outputText;
  fs.writeFileSync(`${root}/${name}.js`, '// Generated by scripts/ai-visual-inspection/sync_web.cjs; edit src instead.\n'+output);
}
const files = fs.readdirSync(root, { recursive: true }).filter(p => fs.statSync(path.join(root, p)).isFile() && p !== 'assets.json');
const assets = Object.fromEntries(files.map(name => {
  const bytes = fs.readFileSync(path.join(root, name));
  return [name, { bytes: bytes.length, gzipBytes: zlib.gzipSync(bytes, { level: 9 }).length, sha256: crypto.createHash('sha256').update(bytes).digest('hex') }];
}));
fs.writeFileSync(`${root}/assets.json`, JSON.stringify({ runtimeVersion: version, assets }, null, 2)+'\n');
const initial = Object.entries(assets).filter(([name]) => /\.(js|mjs|wasm)$/.test(name) || name === 'manifest.json' || name === 'models/balanced-17.onnx').reduce((sum, [, asset]) => sum+asset.gzipBytes, 0);
console.log(JSON.stringify({ runtimeVersion: version, initialGzipBytes: initial, note: 'Local gzip estimate, not measured HTTP transfer; excludes future UI bundle' }));
