"use client";

import { useMemo, useState } from "react";
import { analyzeIndividualsChart, analyzeXbarR, scenarioSubgroups, scenarioValues, type ChartAnalysis, type ControlRuleSet, type ControlChartScenario } from "@/lib/control-chart";
import { trackEvent } from "@/lib/analytics";

type ChartMode = "xbar-r" | "i-mr";
const scenarios = [{id:"stable",label:"正常工程",note:"ランダム"},{id:"shift",label:"平均シフト",note:"中心が移動"},{id:"outlier",label:"単発外れ",note:"1点が変化"},{id:"trend",label:"傾向",note:"徐々に上昇"},{id:"cycle",label:"周期変動",note:"周期的に上下"}] as const;
const ruleSets: {id:ControlRuleSet;label:string;note:string}[]=[{id:"basic",label:"基本",note:"3σ限界外"},{id:"weco",label:"Western Electric",note:"4ルール"},{id:"nelson",label:"Nelson",note:"8ルール"}];
const checks:Record<ControlChartScenario,string>={stable:"大きな異常パターンはありません。管理状態と規格適合は別に確認します。",shift:"変更時刻と材料ロット、設備設定、工具交換、作業者を照合します。",outlier:"削除する前に入力、測定器、材料、設備アラーム、再測定を確認します。",trend:"工具摩耗、暖機、汚れ、環境など時間とともに進む原因を確認します。",cycle:"交代勤務、温度制御、設備サイクル、材料供給の周期と比較します。"};

export function ControlChartLearningTool(){
  const [mode,setMode]=useState<ChartMode>("xbar-r"); const [scenario,setScenario]=useState<ControlChartScenario>("stable"); const [ruleSet,setRuleSet]=useState<ControlRuleSet>("basic"); const [showSpecs,setShowSpecs]=useState(false);
  const xbarResult=useMemo(()=>analyzeXbarR(scenarioSubgroups(scenario),ruleSet),[scenario,ruleSet]); const individualResult=useMemo(()=>analyzeIndividualsChart(scenarioValues(scenario),ruleSet),[scenario,ruleSet]);
  const main=mode==="xbar-r"?xbarResult.xbar:individualResult.individuals; const variation=mode==="xbar-r"?xbarResult.range:individualResult.movingRange; const mainValues=mode==="xbar-r"?xbarResult.means:scenarioValues(scenario); const variationValues=mode==="xbar-r"?xbarResult.ranges:individualResult.mrValues; const allRules=[...main.rules,...variation.rules];
  function selectMode(next:ChartMode){setMode(next);trackEvent("control_chart_type_selected",{type:next});} function selectScenario(next:ControlChartScenario){setScenario(next);trackEvent("control_chart_scenario_selected",{scenario:next});} function selectRules(next:ControlRuleSet){setRuleSet(next);trackEvent("control_chart_rule_set_selected",{rules:next});}
  return <section className="control-chart-tool"><div className="control-chart-setup"><fieldset><legend>1回のタイミングで何個測定しますか？</legend><div><button aria-pressed={mode==="xbar-r"} onClick={()=>selectMode("xbar-r")} type="button"><strong>複数個</strong><span>Xbar-R管理図</span></button><button aria-pressed={mode==="i-mr"} onClick={()=>selectMode("i-mr")} type="button"><strong>1個</strong><span>I-MR管理図</span></button></div></fieldset><fieldset><legend>判定ルール</legend><div>{ruleSets.map((item)=><button aria-pressed={ruleSet===item.id} key={item.id} onClick={()=>selectRules(item.id)} type="button"><strong>{item.label}</strong><span>{item.note}</span></button>)}</div></fieldset></div><header><div><p className="section-label">{mode==="xbar-r"?"XBAR-R / 20 SUBGROUPS × 5":"I-MR / 24 INDIVIDUALS"}</p><h2>{mode==="xbar-r"?"まずRでばらつき、次にXbarで中心を見る":"個別値と隣接差を、時間順に見る"}</h2><p>最初の10群を安定期間として限界を計算し、その後を監視します。</p></div><dl><div><dt>中心線</dt><dd>{main.center.toFixed(2)}</dd></div><div><dt>UCL</dt><dd>{main.ucl.toFixed(2)}</dd></div><div><dt>検出</dt><dd>{allRules.length}</dd></div></dl></header><div className="control-scenarios">{scenarios.map((item)=><button aria-pressed={scenario===item.id} key={item.id} onClick={()=>selectScenario(item.id)} type="button"><strong>{item.label}</strong><span>{item.note}</span></button>)}</div><div className="control-chart-pair"><ChartFigure analysis={variation} title={mode==="xbar-r"?"1. R管理図：群内ばらつき":"1. MR管理図：隣接差"} values={variationValues} /><ChartFigure analysis={main} main showSpecs={showSpecs} title={mode==="xbar-r"?"2. Xbar管理図：工程中心":"2. I管理図：個別値"} values={mainValues} /></div><div className="control-interpretation"><section><p className="section-label">RULE CHECK / {ruleSet.toUpperCase()}</p><h3>{allRules.length?`${allRules.length}種類のシグナルを検出`:scenario==="cycle"?"周期性はルール外でも目で確認":"選択ルールではシグナルなし"}</h3><ul>{allRules.length?allRules.map((rule,index)=><li data-found="true" key={`${rule.id}-${index}`}><span>検出</span>{rule.label}</li>):<li><span>—</span>追加調査を求めるルールなし</li>}</ul><small>{ruleSet==="basic"?"基本は3σ限界外だけを検出します。":ruleSet==="weco"?"小さなシフトに敏感になりますが、誤警報も増えます。":"8種類を確認します。R・MRでは適用可能なTest 1〜4に限定します。"}</small></section><section><p className="section-label">NEXT CHECK</p><h3>次に何を確認する？</h3><p>{checks[scenario]}</p></section></div><div className="control-limits-lesson"><div><p className="section-label">CONTROL LIMITS VS SPECIFICATIONS</p><h3>管理限界と規格限界は、別の境界</h3><p>管理限界は工程データ、規格限界は顧客・設計・社内要求から決まります。</p></div><button aria-pressed={showSpecs} onClick={()=>setShowSpecs((v)=>!v)} type="button"><span>{showSpecs?"規格限界を表示中":"規格限界は非表示"}</span><strong>{showSpecs?"規格内でも管理状態とは限らない":"規格限界を重ねて比較する"}</strong></button></div></section>;
}

function ChartFigure({analysis,values,title,main=false,showSpecs=false}:{analysis:ChartAnalysis;values:number[];title:string;main?:boolean;showSpecs?:boolean}){const min=Math.min(analysis.lcl,...values,...(main&&showSpecs?[95]:[]))-.5;const max=Math.max(analysis.ucl,...values,...(main&&showSpecs?[105]:[]))+.5;const x=(i:number)=>50+i/Math.max(values.length-1,1)*800;const y=(v:number)=>220-(v-min)/(max-min)*165;return <figure className="control-chart-figure"><strong>{title}</strong><svg viewBox="0 0 900 260" role="img" aria-label={title}><rect x="43" y="35" width="814" height="190" rx="6" /><rect className="control-baseline-area" x="43" y="35" width={x(Math.min(9,values.length-1))-43} height="190" />{main&&showSpecs&&<><line className="control-spec-line" x1="43" x2="857" y1={y(105)} y2={y(105)}/><line className="control-spec-line" x1="43" x2="857" y1={y(95)} y2={y(95)}/></>}<line className="control-limit-line" x1="43" x2="857" y1={y(analysis.ucl)} y2={y(analysis.ucl)}/><line className="control-center-line" x1="43" x2="857" y1={y(analysis.center)} y2={y(analysis.center)}/><line className="control-limit-line" x1="43" x2="857" y1={y(analysis.lcl)} y2={y(analysis.lcl)}/><path className="control-data-line" d={values.map((v,i)=>`${i?"L":"M"}${x(i)},${y(v)}`).join(" ")}/>{values.map((v,i)=><circle className={analysis.flaggedPoints.has(i)?"is-alert":""} cx={x(i)} cy={y(v)} key={i} r={analysis.flaggedPoints.has(i)?6:4}/>)}</svg><figcaption>青は測定統計量、赤は選択中のルールで検出された点です。</figcaption></figure>}
