"use client";

import { useMemo, useState } from "react";
import { analyzeIndividualsChart, analyzeXbarR, detectControlRules, scenarioSubgroups, scenarioValues, stableNormalSequence, type ChartAnalysis, type ControlRuleSet, type ControlChartScenario } from "@/lib/control-chart";
import { trackEvent } from "@/lib/analytics";

type ChartMode = "xbar-r" | "i-mr";
const scenarios = [{id:"stable",label:"正常工程",note:"ランダム"},{id:"shift",label:"平均シフト",note:"中心が移動"},{id:"outlier",label:"単発外れ",note:"1点が変化"},{id:"trend",label:"傾向",note:"徐々に上昇"},{id:"cycle",label:"周期変動",note:"周期的に上下"}] as const;
const ruleSets:{id:ControlRuleSet;label:string;note:string}[]=[{id:"basic",label:"基本",note:"3σ管理限界外"},{id:"weco",label:"Western Electric",note:"4ルール"},{id:"nelson",label:"Nelson",note:"8ルール"}];
const checks:Record<ControlChartScenario,string>={stable:"大きな異常パターンはありません。管理状態と規格適合は別に確認します。",shift:"変更時刻と材料ロット、設備設定、工具交換、作業者を照合します。",outlier:"削除する前に入力、測定器、材料、設備アラーム、再測定を確認します。",trend:"工具摩耗、暖機、汚れ、環境など時間とともに進む原因を確認します。",cycle:"交代勤務、温度制御、設備サイクル、材料供給の周期と比較します。"};

export function ControlChartLearningTool(){
  const [mode,setMode]=useState<ChartMode>("xbar-r");
  const [scenario,setScenario]=useState<ControlChartScenario>("stable");
  const [ruleSet,setRuleSet]=useState<ControlRuleSet>("basic");
  const [showSpecs,setShowSpecs]=useState(false);
  const [monitoringPoints,setMonitoringPoints]=useState(100);
  const comparisons=useMemo(()=>ruleSets.map((item)=>{if(mode==="xbar-r"){const result=analyzeXbarR(scenarioSubgroups(scenario),item.id);return {...item,main:result.xbar,variation:result.range,mainValues:result.means,variationValues:result.ranges};}const result=analyzeIndividualsChart(scenarioValues(scenario),item.id);return {...item,main:result.individuals,variation:result.movingRange,mainValues:scenarioValues(scenario),variationValues:result.mrValues};}),[mode,scenario]);
  const current=comparisons.find((item)=>item.id===ruleSet)??comparisons[0];
  const allRules=[...current.main.rules,...current.variation.rules];
  const falseAlarmComparison=useMemo(()=>{const values=stableNormalSequence(monitoringPoints);return ruleSets.map((item)=>{const rules=detectControlRules(values,100,1,item.id);return {...item,rules,points:new Set(rules.flatMap((rule)=>rule.points)).size};});},[monitoringPoints]);
  function selectMode(next:ChartMode){setMode(next);trackEvent("control_chart_type_selected",{type:next});}
  function selectScenario(next:ControlChartScenario){setScenario(next);trackEvent("control_chart_scenario_selected",{scenario:next});}
  function selectRules(next:ControlRuleSet){setRuleSet(next);trackEvent("control_chart_rule_set_selected",{rules:next});}
  return <section className="control-chart-tool">
    <div className="control-chart-setup"><fieldset><legend>1回のタイミングで何個測定しますか？</legend><div><button aria-pressed={mode==="xbar-r"} onClick={()=>selectMode("xbar-r")} type="button"><strong>複数個</strong><span>Xbar-R管理図</span></button><button aria-pressed={mode==="i-mr"} onClick={()=>selectMode("i-mr")} type="button"><strong>1個</strong><span>I-MR管理図</span></button></div></fieldset><fieldset><legend>判定ルール</legend><div>{ruleSets.map((item)=><button aria-pressed={ruleSet===item.id} key={item.id} onClick={()=>selectRules(item.id)} type="button"><strong>{item.label}</strong><span>{item.note}</span></button>)}</div></fieldset></div>
    <header><div><p className="section-label">{mode==="xbar-r"?"XBAR-R / 20 SUBGROUPS × 5":"I-MR / 24 INDIVIDUALS"}</p><h2>{mode==="xbar-r"?"まずRでばらつき、次にXbarで中心を見る":"個別値と隣接差を、時間順に見る"}</h2><p>最初の10群を安定期間として限界を計算し、その後を監視します。</p></div><dl><div><dt>中心線</dt><dd>{current.main.center.toFixed(2)}</dd></div><div><dt>UCL</dt><dd>{current.main.ucl.toFixed(2)}</dd></div><div><dt>検出</dt><dd>{allRules.length}</dd></div></dl></header>
    <div className="control-scenarios">{scenarios.map((item)=><button aria-pressed={scenario===item.id} key={item.id} onClick={()=>selectScenario(item.id)} type="button"><strong>{item.label}</strong><span>{item.note}</span></button>)}</div>
    <section className="control-rule-comparison"><header><div><p className="section-label">SAME DATA / DIFFERENT SENSITIVITY</p><h3>同じデータを、3つのルールで比べる</h3></div><p>カードを選ぶと、管理図の検出点も切り替わります。</p></header><div>{comparisons.map((item)=>{const rules=[...item.main.rules,...item.variation.rules];const points=new Set([...item.main.flaggedPoints,...item.variation.flaggedPoints]);return <button aria-pressed={ruleSet===item.id} key={item.id} onClick={()=>selectRules(item.id)} type="button"><span>{item.label}</span><strong>{rules.length?<>{rules.length}<small>種類を検出</small></>:<>検出なし</>}</strong><i>{points.size?`${points.size}点を強調`:item.id==="basic"?"3σ外のみ確認":"追加パターンなし"}</i></button>})}</div><footer>{comparisons[0].main.rules.length===0&&comparisons.slice(1).some((item)=>item.main.rules.length>0)?"3σ管理限界を超えなくても、点の並びから小さな変化を検出できます。":"ルールを増やしても結果が同じ場合があります。感度を上げる目的を先に決めます。"}</footer></section>
    <section className="control-false-alarm"><header><div><p className="section-label">FALSE SIGNAL SIMULATION</p><h3>安定工程でも、偶然のシグナルは出る</h3><p>平均100・σ1から作った同じ疑似データへ、3つのルールを適用します。</p></div><label><span>監視する点数 <b>{monitoringPoints}点</b></span><input min="50" max="500" step="50" type="range" value={monitoringPoints} onChange={(event)=>setMonitoringPoints(Number(event.target.value))}/></label></header><div>{falseAlarmComparison.map((item)=><article key={item.id}><span>{item.label}</span><strong>{item.points}<small> 点を確認対象に</small></strong><i>{item.rules.length?`${item.rules.length}種類のルールが反応`:"シグナルなし"}</i></article>)}</div><footer><strong>これは「本当に異常があった」点数ではありません。</strong><p>生成元は変化のない安定工程です。ルールの反応は調査のきっかけであり、特殊原因の存在を自動的に証明するものではありません。</p></footer></section>
    <div className="control-chart-pair"><ChartFigure analysis={current.variation} title={mode==="xbar-r"?"1. R管理図：群内ばらつき":"1. MR管理図：隣接差"} values={current.variationValues}/><ChartFigure analysis={current.main} main showSpecs={showSpecs} title={mode==="xbar-r"?"2. Xbar管理図：工程中心":"2. I管理図：個別値"} values={current.mainValues}/></div>
    <div className="control-interpretation"><section><p className="section-label">RULE CHECK / {ruleSet.toUpperCase()}</p><h3>{allRules.length?`${allRules.length}種類のシグナルを検出`:scenario==="cycle"?"周期性はルール外でも目で確認":"選択ルールではシグナルなし"}</h3><ul>{allRules.length?allRules.map((rule,index)=><li data-found="true" key={`${rule.id}-${index}`}><span>検出</span>{rule.label}</li>):<li><span>—</span>追加調査を求めるルールなし</li>}</ul><small>{ruleSet==="basic"?"基本は3σ管理限界外だけを検出します。":ruleSet==="weco"?"小さなシフトに敏感になりますが、誤警報も増えます。":"8種類を確認します。R・MRではTest 1〜4に限定します。"}</small></section><section><p className="section-label">NEXT CHECK</p><h3>次に何を確認する？</h3><p>{checks[scenario]}</p></section></div>
    <div className="control-limits-lesson"><div><p className="section-label">CONTROL LIMITS VS SPECIFICATIONS</p><h3>管理限界と規格限界は、別の境界</h3><p>管理限界は工程データ、規格限界は顧客・設計・社内要求から決まります。</p></div><button aria-pressed={showSpecs} onClick={()=>setShowSpecs((value)=>!value)} type="button"><span>{showSpecs?"規格限界を表示中":"規格限界は非表示"}</span><strong>{showSpecs?"規格内でも管理状態とは限らない":"規格限界を重ねて比較する"}</strong></button></div>
  </section>;
}

function ChartFigure({analysis,values,title,main=false,showSpecs=false}:{analysis:ChartAnalysis;values:number[];title:string;main?:boolean;showSpecs?:boolean}){const min=Math.min(analysis.lcl,...values,...(main&&showSpecs?[95]:[]))-.5;const max=Math.max(analysis.ucl,...values,...(main&&showSpecs?[105]:[]))+.5;const x=(index:number)=>50+index/Math.max(values.length-1,1)*800;const y=(value:number)=>220-(value-min)/(max-min)*165;return <figure className="control-chart-figure"><strong>{title}</strong><svg viewBox="0 0 900 260" role="img" aria-label={title}><rect x="43" y="35" width="814" height="190" rx="6"/><rect className="control-baseline-area" x="43" y="35" width={x(Math.min(9,values.length-1))-43} height="190"/>{main&&showSpecs&&<><line className="control-spec-line" x1="43" x2="857" y1={y(105)} y2={y(105)}/><line className="control-spec-line" x1="43" x2="857" y1={y(95)} y2={y(95)}/></>}<line className="control-limit-line" x1="43" x2="857" y1={y(analysis.ucl)} y2={y(analysis.ucl)}/><line className="control-center-line" x1="43" x2="857" y1={y(analysis.center)} y2={y(analysis.center)}/><line className="control-limit-line" x1="43" x2="857" y1={y(analysis.lcl)} y2={y(analysis.lcl)}/><path className="control-data-line" d={values.map((value,index)=>`${index?"L":"M"}${x(index)},${y(value)}`).join(" ")}/>{values.map((value,index)=><circle className={analysis.flaggedPoints.has(index)?"is-alert":""} cx={x(index)} cy={y(value)} key={index} r={analysis.flaggedPoints.has(index)?6:4}/>)}</svg><figcaption>青は測定統計量、赤は選択中のルールで検出された点です。</figcaption></figure>}
