const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
function loader(overrides={}){const cache=new Map();function load(file){const filename=[file,file+'.ts',file+'.tsx',path.join(file,'index.ts')].find(p=>fs.existsSync(p)&&fs.statSync(p).isFile());if(!filename)throw Error(file);if(cache.has(filename))return cache.get(filename);const exports={};cache.set(filename,exports);const code=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;vm.runInNewContext(code,{exports,process,URL,TextEncoder,require(id){if(id in overrides)return overrides[id];if(id==='@/lib/analytics')return{trackEvent(){}};if(id==='next/link')return{__esModule:true,default:({children,...props})=>React.createElement('a',props,children)};if(id.endsWith('.css'))return{__esModule:true,default:new Proxy({},{get:(_,key)=>key})};if(id.startsWith('@/'))return load('src/'+id.slice(2));if(id.startsWith('.'))return load(path.resolve(path.dirname(filename),id));return require(id)}},{filename});return exports}return load}
const load=loader(),data=load('src/data/improvement-report'),calc=load('src/lib/process-comparison'),report=load('src/lib/improvement-report'),workspace=load('src/lib/tool-workspace');
const input=load('src/data/process-comparison-sample').processComparisonSample,result=calc.compareProcesses(input);
const rows=report.capabilityRows(result);assert.deepEqual(Array.from(rows,r=>r[0]),['Pp','Ppk']);
assert.ok(Math.abs(Number(rows[0][1])-(102-98)/(6*result.a.sd))<1e-8);
for(const [lower,upper,label] of [['','102','Ppu'],['98','','Ppl']])assert.equal(report.capabilityRows(calc.compareProcesses({...input,lower,upper}))[0][0],label);
assert.equal(report.capabilityRows(calc.compareProcesses({...input,lower:'',upper:''})).length,0);
assert.match(report.capabilityRows(calc.compareProcesses({...input,dataA:'100\n100'}))[0][1],/算出不可/);
const large=calc.compareProcesses({...input,dataA:'-8e307\n8e307',dataB:'-7e307\n7e307',lower:'-8e307',upper:'8e307'});assert.ok(Number(report.capabilityRows(large)[0][1])>0);
const infinity={...result,a:{...result.a,sd:Number.MIN_VALUE}};assert.match(report.capabilityRows(infinity)[0][1],/算出不可/);
assert.ok(report.reportObservations(result).every(s=>!s.includes('改善成功')&&!s.includes('有意')));
const saved={...input,...data.sampleReportNotes};const text=workspace.serializeWorkspace('improvement-report',saved);assert.deepEqual(JSON.parse(JSON.stringify(workspace.parseWorkspace(text,'improvement-report'))),JSON.parse(JSON.stringify(saved)));
const legacy=workspace.serializeWorkspace('process-comparison',input);const converted=workspace.parseWorkspace(legacy,'improvement-report');assert.equal(converted.reportTitle,'');assert.equal(converted.dataA,input.dataA);
assert.throws(()=>workspace.parseWorkspace(text,'process-comparison'));assert.throws(()=>workspace.serializeWorkspace('improvement-report',{...saved,reportTitle:'a'.repeat(61)}));assert.throws(()=>workspace.serializeWorkspace('improvement-report',{...saved,reportDate:'2026-02-30'}));
assert.equal(data.reportNotesErrors({...data.emptyReportNotes,interpretation:'字'.repeat(180)}).length,0);assert.equal(data.reportNotesErrors({...data.emptyReportNotes,interpretation:'字'.repeat(181)}).length,1);
const Preview=load('src/components/ImprovementReportPreview').ImprovementReportPreview;const html=renderToStaticMarkup(React.createElement(Preview,{result,notes:{...data.sampleReportNotes,interpretation:'<script>alert(1)</script>'}}));assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;script&gt;'));for(const value of ['Pp','Ppk','本人の記述','自動の観察文','mfg-compass.com'])assert.ok(html.includes(value));
function nodes(tree,p){if(!tree||typeof tree!=='object')return[];if(Array.isArray(tree))return tree.flatMap(n=>nodes(n,p));return[...(p(tree)?[tree]:[]),...nodes(tree.props?.children,p)]}
let cursor=0;const slots=[];const react={...React,useState(initial){const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],value=>{slots[i]=typeof value==='function'?value(slots[i]):value}]},useRef(initial){const i=cursor++;return slots[i]??={current:initial}},useEffect(){}};
const interactive=loader({react});const Component=interactive('src/components/ProcessComparisonTool').ProcessComparisonTool;function render(){cursor=0;return Component({reportMode:true})}function button(label){return nodes(render(),n=>n.type==='button'&&n.props.children===label)[0]}function child(name){return nodes(render(),n=>n.type?.name===name)[0]}
button('架空例で試す').props.onClick();assert.ok(child('ImprovementReportEditor').props.result);assert.equal(child('ImprovementReportEditor').props.notes.reportTitle,data.sampleReportNotes.reportTitle);
const oldNotes=child('ImprovementReportEditor').props.notes;nodes(render(),n=>n.type==='input')[0].props.onChange({target:{value:'changed'}});assert.equal(child('ImprovementReportEditor').props.result,null);assert.equal(child('ImprovementReportEditor').props.notes,oldNotes);
child('ToolWorkspaceFile').props.onRestore(saved);assert.equal(child('ImprovementReportEditor').props.result,null);assert.equal(child('ImprovementReportEditor').props.notes.reportDate,saved.reportDate);
const page=load('src/app/(ja)/tools/improvement-report/page');assert.equal(page.metadata.robots.index,true);assert.equal(page.metadata.alternates.canonical,data.improvementReportMeta.route);const pageHtml=renderToStaticMarkup(React.createElement(page.default));assert.ok(pageHtml.includes('WebApplication'));assert.ok(pageHtml.includes('BreadcrumbList'));
assert.ok(load('src/app/sitemap').default().some(r=>r.url.endsWith(data.improvementReportMeta.route)&&r.lastModified));assert.equal(load('src/data/learning-tools').learningTools.filter(t=>t.id==='improvement-report').length,1);
console.log('PASS: report calculations, scale safety, one-sided/no limits, zero SD, file compatibility, dates/lengths, escaping, stale result invalidation, SSR and publication.');

const analytics=[];const actions=loader({'@/lib/analytics':{trackEvent:(name,props)=>analytics.push({name,props})}})('src/components/ImprovementReportEditor');
for(const action of ['open_editor','print_requested','feedback_click'])actions.reportAction(action);
assert.deepEqual(JSON.parse(JSON.stringify(analytics)),['open_editor','print_requested','feedback_click'].map(action=>({name:'improvement_report_action',props:{tool_id:'improvement-report',action,locale:'ja'}})));
console.log('PASS: report analytics fixed categories only.');
