const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const ts = require('typescript');
function load(file) {
  const exports = {};
  const code = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2017 } }).outputText;
  vm.runInNewContext(code, { exports, require: name => load(path.resolve(path.dirname(file), name + '.ts')) }, { filename: file });
  return exports;
}
const { emptyWorkstyleNote: empty, getWorkstyleCards: cards, updateWorkstyleSelection: select, buildWorkstyleNote: build } = load(path.resolve(__dirname, '../../src/lib/workstyle-check.ts'));
assert.equal(cards(empty).length, 0);
const unknown = select(empty, [], { night: 'learn' });
assert.equal(cards(unknown)[0].role, '職種は未定');
assert.match(build(unknown), /未確認/);
const pair = select(empty, ['process', 'field'], { travel: 'learn', night: 'avoid' });
assert.equal(cards(pair).length, 4);
assert.equal(cards(pair)[0].condition, '夜勤');
assert.notEqual(cards(pair)[0].question, cards(pair)[1].question);
const marked = { ...pair, confirmations: { 'process:night': 'fits', 'field:night': 'conflicts' }, excluded: ['process:night'] };
assert.match(build(marked), /本人の確認状況/);
assert.doesNotMatch(build(marked), /量産対応と工程開発の業務割合/);
assert.match(build(marked), /応募を保留・見送る/);
const changed = select(marked, ['maintenance'], { night: 'avoid' });
assert.equal(Object.keys(changed.confirmations).length, 0);
assert.equal(changed.excluded.length, 0);
assert.doesNotMatch(build(changed), /条件を満たす/);
const removed = select(marked, pair.roles, { travel: 'learn' });
assert.equal(Object.keys(removed.confirmations).length, 0);
const restored = select(removed, pair.roles, pair.conditions);
assert.equal(restored.confirmations['process:night'], undefined);
const importance = select(marked, pair.roles, { ...pair.conditions, night: 'conditional' });
assert.equal(importance.confirmations['process:night'], 'fits');
assert.equal(marked.confirmations['process:night'], 'fits');
assert.equal(select(empty, ['process', 'process', 'maintenance', 'field'], { night: 'avoid', call: 'learn', travel: 'learn', cleanroom: 'learn' }).roles.length, 2);
assert.equal(Object.keys(select(empty, [], { night: 'avoid', call: 'learn', travel: 'learn', cleanroom: 'learn' }).conditions).length, 3);
const allExcluded = { ...pair, excluded: cards(pair).map(card => card.id) };
assert.match(build(allExcluded), /質問は選んでいません/);
console.log('PASS: unknown role, comparison, priority, note attribution, selection cleanup, bounds, empty questions');
